name = "chatbot-studio-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "chatbot-studio-api-prod"

[env.production.vars]
ENVIRONMENT = "production"

# Secrets (set with: wrangler secret put SECRET_NAME)
# DATABASE_URL
# JWT_SECRET
# JWT_REFRESH_SECRET
# SMTP_HOST
# SMTP_PORT
# SMTP_USER
# SMTP_PASS
